<?php

namespace BookEditorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function deleteEvent($events){
        foreach($events as $event){
            $query = $this->createQueryBuilder('q')
                ->setMaxResults(3)
                ->getQuery();
            return $query->getResult();
        }

    }
}
