<?php

namespace BookEditorBundle\Repository;

/**
 * PressArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
