INSERT INTO rdm.book (title, author, description, facebook_link_url, image_url, press_title, press_image_url, release_date, purchase_order_image_url) VALUES ('Le Petit Bacchus', 'Benjamin Poussardin', 'Passionné de vin et de gastronomie, présent toute l’année aux côtés des vignerons, j’ai créé "Le Petit Bacchus" afin de vous faciliter l’accès à la dégustation du vin. Ce carnet a été développé de manière simple et ludique. Il vous permettra de placer très rapidement des mots sur ce que vous voyez, sentez et goûtez.
Il vous donnera l’opportunité de vous souvenir de vos coups de cœurs, de vos meilleurs rapports prix/plaisir, ainsi que de vos rencontres avec les vignerons.
Cet outil vous aidera également à être plus à l’aise dans votre relation avec le vin : repas de famille, repas professionnels, discussions entre amis... Synonyme d’art et de culture, l’œnologie vous offre l’occasion d’aborder de nombreux sujets tout aussi passionnants : géographie, histoire, littérature, photographie, voyages, arts plastiques, etc.
Le vin, une question de bon(s) sens !', '#', '06e1d6c7085ef988f186daa2eb6d28a0.jpeg', 'La Presse en parle', 'aa7403a4544e16614c26fcf9594076b6.png', '2011-01-01 00:00:00', '605b7d469c6f46f18fb383dfcbaa9614.png');
INSERT INTO rdm.book (title, author, description, facebook_link_url, image_url, press_title, press_image_url, release_date, purchase_order_image_url) VALUES ('L''île Sacrée', 'Catherine Pierdat', 'L’abbé Henri Boudet est curé de Rennes-les-Bains, petite station thermale très prisée en cette fin de dix-neuvième siècle. Il publie en 1886 un livre singulier et obscur : « La Vraie Langue celtique et le Cromleck de Rennes-les-Bains » dans lequel il prétend restituer la langue originelle grâce à l’anglais moderne, très proche, selon lui, de la langue des Tectosages, tribu celte du sud-ouest de la Gaule.
Pour la première fois, La Vraie Langue celtique de l’abbé Boudet est entièrement décodée. Après quatre ans de travail acharné et méthodique, l’auteur de L’Île Sacrée met au jour un double secret — d’État et d’Église — jusqu’ici totalement oublié des historiens....
Livre historique et passionnant à découvrir, c’est un magnifique cadeau à offrir ou à s’offrir pour Noël ou toutes autres circonstances. Réservez dès à présent votre livre....', 'lorem', 'b7f5072ea0dde4e121633cb567c606c6.jpeg', 'La Presse en parle', '4f5dd27e615775dd9bec4e4ec93b9b0e.png', '2011-01-01 00:00:00', 'f779eed3bf4fd72361ecd70790f4f980.png');
INSERT INTO rdm.book (title, author, description, facebook_link_url, image_url, press_title, press_image_url, release_date, purchase_order_image_url) VALUES ('Découvertes Gourmandes', 'Paul Bocuse', 'Rhône-Alpes Passions se met à table et présente ses "Découvertes gourmandes" issues de la région Rhône-Alpes.
Partez à la rencontre de 46 passionnés issus des métiers de bouche de la région Rhône-Alpes avec comme particularité et fil rouge le vécu d’un parcours souvent riche en émotions, rencontres et échanges.
Des hommes et des femmes, certes au service de notre quotidien, qui travaillent toujours dans l’excellence et la passion pour révéler le meilleur à nos papilles gustatives.

Des motivations suprêmes pour avancer dans ces professions, dont l’unique objectif est de donner du plaisir gourmand au plus grand nombre d’entre nous...

Un grand Monsieur au service de la gastronomie de France...merci pour votre soutien mon cher Paul Bocuse à cet ouvrage.

Une seule envie : dévorer ce livre !', 'Ipsum', '7a4284db8e9cffbe349b356a9ef618c2.jpeg', 'La Presse en parle', 'c730f7da93bec323cee3ccfe24e7042d.png', '2011-01-01 00:00:00', 'f1788319e1f4a1826175e169b5216f41.png');
INSERT INTO rdm.book (title, author, description, facebook_link_url, image_url, press_title, press_image_url, release_date, purchase_order_image_url) VALUES ('L''Afficheur tombe dans le panneau', 'Dominique Guichard', 'Du monde qui nous entoure, de l’immédiat et du quotidien au présent, même si par précaution l’action se déroule dans les années 80. Mais il y a forcément un passé, le sien n’est fait que de fugaces réminiscences et c’est un peu le moteur du présent, et il a un avenir, sauf que le sien n’a pas de but si ce n’est d’aider ses amis, ses proches ses rencontres, et c’est le carburant du présent. Par son métier il est dehors, dans la rue où il voit la ville depuis le coin du trottoir jusqu’à toute l’agglomération. C’est un urbain qui vit aux pulsations de la cité selon l’heure du jour et la saison. C’est un grand témoin qui veut rester en retrait, mais ne peut s’empêcher d’intervenir pour aider, selon son instinct ou à la demande ses amis. Il déguste aussi le parler lyonnais, qui enjolive ses échanges. Son passé, avant Lyon, fut radicalement différent de son présent, il s’en sert pour aider, jamais pour se valoriser. On ne sait pas vraiment d’où il vient et il ne sait pas où il va, mais seulement où il est.', 'loremipsum', 'ffc05d6317ca1a71c969dba5725202c1.jpeg', 'La Presse en parle', 'bd225a6f9da94369a7aa2a98546ac01b.png', '2011-01-01 00:00:00', '9ca3261673bcadea4ec47ba9eaea79f7.png');
INSERT INTO rdm.book (title, author, description, facebook_link_url, image_url, press_title, press_image_url, release_date, purchase_order_image_url) VALUES ('Les Pierres Dorées, émotions et images...', 'Laurence Chabalier', 'Sans doute avez-vous perçu au fil du temps, ma tendresse, mon amour, voire ma passion pour les petits « Villages du Beaujolais en Pierres Dorées » que je découvre au gré de mes pas : découvertes de scènes touchantes ou évocatrices d’instants de vie, lumières et couleurs, chaleur des pierres, douceur vallonnée des paysages de vignes...

Ce plaisir des découvertes, ces lieux que j''affectionne, je souhaite les partager avec vous au travers d’un ouvrage photographique d’une centaine de pages...témoignages de ces jolis pétales d’une vie simple que je me suis plu à effeuiller au gré des années et des saisons.... Au gré de mes pas...quelques jolies découvertes...des scènes lumineuses au cœur du Beaujolais des Pierres Dorées...', 'grrrr', '7590c69632a5258e545fdc1b5d1b86af.jpeg', 'La Presse en parle', '760b33ad40255ada67e4741aaf7dd274.jpeg', '2011-01-01 00:00:00', 'a38d25726e7a464c727f7c6dda9d7fbd.jpeg');
INSERT INTO rdm.book (title, author, description, facebook_link_url, image_url, press_title, press_image_url, release_date, purchase_order_image_url) VALUES ('Mousselines au fil du temps, une édition haute en couleurs', 'Christelle Beauvent', 'L’ouvrage retrace l’histoire de l’organisation des Mousselines 2015 de la 1ère réunion (18 avril 2014) à la fin de l’événement (le grand défilé avec concert et feu d’artifice du 28 juin 2015) au travers d’un livre de photographies légendées. Au fil des pages et des photographies, découvrez toute l’organisation, pendant plus d''un an, au travers de la mobilisation humaine avec de nombreux bénévoles ainsi que l’ensemble des habitants de Tarare pour aboutir à une véritable réussite.', 'hum', 'b77a8d41b847512116758d4e667d25e3.jpeg', 'La Presse en parle', '67fb4e9ac5267e52e3ee0405e62d4d2c.jpeg', '2011-01-01 00:00:00', '81d38d64c041dee9129e8b5b5ec8b404.jpeg');
INSERT INTO rdm.book (title, author, description, facebook_link_url, image_url, press_title, press_image_url, release_date, purchase_order_image_url) VALUES ('Coeur de vigneron', 'Sandrine Vadrot-Morel', 'Dégustons un verre de vin : le vigneron y a déposé une part de son âme et une pincée de son cœur. Balade que vous propose cet ouvrage...

Travail de la vigne et du vin, légendes, dictons et proverbes... contés au fil des mois.', 'ahah', '60ad72a067609374407439f0a491cd9b.jpeg', 'La Presse en parle', '2da76a55b0a7649bebf3a21e7366f523.png', '2011-01-01 00:00:00', '0d387d22b40b281ebb546c3eb6762954.jpeg');
INSERT INTO rdm.book (title, author, description, facebook_link_url, image_url, press_title, press_image_url, release_date, purchase_order_image_url) VALUES ('Voyages d''un chien amoureux', 'François Jean-Marie Mercier', 'Albert, un architecte célibataire à la retraite rencontre Bernadette, une psychothérapeute, elle aussi à la recherche d’une âme sœur, dont il tombe amoureux… mais qui lui cache l’existence d’un autre compagnon... Albert est obsédé par des cauchemars récurrents qui peu à peu vont lui faire découvrir son identité réelle. Cette aventure est l’occasion d’un voyage initiatique au cœur de lui même qui va le conduire jusqu''en Roumanie où il va faire d’autres rencontres et découvrir d’autres réalités… Ce roman est le prétexte à des réflexions philosophiques, culturelles, ésotériques et spirituelles de l’auteur.', 'none', 'fe481966a6db8dd57af9d256a8afed86.jpeg', 'La Presse en parle', '993ed7c55516bfc0c3289149d6b9dec4.png', '2011-01-01 00:00:00', '76e85aafefb5c66a1caf68efcf3f5541.png');
INSERT INTO rdm.book (title, author, description, facebook_link_url, image_url, press_title, press_image_url, release_date, purchase_order_image_url) VALUES ('Un instant éclairé', 'Bertrand Mouret', 'LeGraphistographe est de ceux qui vous charment autant qu’ils vous dérangent. Et en plus, il adore ça. Derrière son appareil, il a cette capacité à creuser, à saisir des émotions dans leur intégrité et sans toujours les nommer puisque souvent ses photos parlent d’elles-mêmes. Son objectif est saisissant, son regard ressemble à celui du prédateur qui, loin d’être destructeur ou chasseur, tente d’abord de voir puis de montrer. Il sent, fixe les gens, arpente les rues et tourne autour des bâtiments pour mieux les immortaliser.', 'https://www.facebook.com/events/1249063985103633/', '174650825fbcf40e5db1513ee991a72c.jpeg', 'La Presse en parle', '75e4811e8eb74da03af6324001b20e3f.png', '2011-01-01 00:00:00', '07af070cff7643251c6c302737c6d8e1.jpeg');